---
name: playbook-demo
pack: mydemo
description: Playbook Demo
runner_type: orquesta
entry_point: workflows/playbook-demo.yaml
parameters:
  playbook:
    required: true
    type: string
    default: /opt/stackstorm/packs/ansible/playbook/ping.yaml
  inventory_file:
    required: true
    type: string
    default: /opt/stackstorm/packs/ansible/inventory/hosts
