---
name: "notify"
pack: "mydemo"
# ref
# https://docs.stackstorm.com/chatops/notifications.html
description: "rule firing on action completion."
enabled: true

trigger:
  type: "core.st2.generic.notifytrigger"
  parameters: {}
criteria:
  trigger.channel:
    pattern: "slack"
    type: "equals"
action:
  ref: "slack.post_message"
  parameters:
    message: "{{trigger.message}}"