---
name: "timer"
pack: "mydemo"
description: "run mydemo per 300 secs"
enabled: true

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    unit: seconds
    #delta: 30
    delta: 300

action:
  ref: "mydemo.deploy-container-overview"
  parameters:
    working_dir: /usr/src/app/flask-docker
    branch: master
    containers_name:
      - flask-docker_flask
      - flask-docker_nginx
    rebuilding_time: 600

