---
name: "timer"
pack: "mydemo"
description: "run mydemo per 60 secs"
enabled: true

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    unit: seconds
    #delta: 30
    delta: 300

action:
  ref: "mydemo.deploy-container-init"
  parameters:
    working_dir: /usr/src/app/flask-docker
    branch: master

