version: 1.0

description: playbook-demo

input:
  - playbook
  - inventory_file

tasks:
  playbook:
    action: ansible.playbook
    input:
      playbook: <% ctx().playbook %>
      inventory_file: <% ctx().inventory_file %>
    next:
      - when: <% succeeded() %>
        do: echo
        publish: 
          - msg: <% result() %>
      - when: <% failed() %>
        publish: 
          - msg: <% result() %>

  echo:
    action: core.local
    input:
      cmd: echo <% ctx().msg %> 
    next:
      - when: <% succeeded() %>
        do: last
        publish:
          - msg: <% result() %>
      - when: <% failed() %>
        do: fail
        publish: 
          - msg: <% result() %>

  last:
    action: slack.post_message
    input:
      message: <% ctx().msg %>
    next:
      - when: <% succeeded() %>
        publish:
          - msg: <% result() %>
      - when: <% failed() %>
        do: 
          - last
          - fail
        publish:
          - msg: <% result() %>

output:
  - msg: <% ctx().msg %>
