---
- hosts: junos
  connection: netconf
  gather_facts: no

  # ref
  # slack – Send Slack notifications
  # https://docs.ansible.com/ansible/latest/modules/slack_module.html?highlight=slack
  # Ansible ネットワークモジュールにおける facts の扱い
  # https://tekunabe.hatenablog.jp/entry/2018/05/04/ansible_net_facts

  tasks:
    - name: facts
      junos_facts:
      register: junos

    - name: debug
      debug:
        msg: "{{ junos.facts | default('None', true) }}"
    
    - name: Use the attachments API
      slack:
        username: "{{ lookup('env', 'SLACKBOT_NAME') | default('ansibleBot')  }}"
        token: "{{ lookup('env', 'INCOMING_WEBHOOK_URL_SLACKFORMAT') }}"
        channel: "{{ lookup('env', 'DST_CHANNEL') }}"
        attachments:
          - title: Display Junos Facts
            text: "{{ inventory_hostname }}"
            color: '#ff00dd'
            fields:
              - title: "Gather Facts"
                value: "{{ junos.facts | default('None', true) }}"
                short: False