---
- hosts: junos
  connection: network_cli
  gather_facts: no
  become: yes

  tasks:
    - name: show version
      junos_command:
        commands:
          - show version
          - show interface terse
      when: ansible_network_os == "junos"
      register: result
    - debug: 
        msg: "{{ result.stdout_lines }}"

