---
- hosts: junos
  connection: network_cli
  gather_facts: no

  tasks:
    - name: show version
      junos_command:
        commands: show version
      register: result
      when: ansible_network_os == "junos"
    - debug: 
        msg: "{{ result.stdout_lines[0] }}"

