---
- hosts: junos
  connection: network_cli
  gather_facts: no
  become: yes

  tasks:
    - name: show version
      junos_command:
          - show version
          - show interface terse
      register: result
      when: ansible_network_os == "junos"
    #- debug: 
    #    msg: "{{ result }}"

