---
- hosts: localhost
  become: yes
  connection: local

  # Ansible ネットワークモジュールにおける facts の扱い
  # https://tekunabe.hatenablog.jp/entry/2018/05/04/ansible_net_facts

  tasks:
    - shell: ping -c 5 -w 5 localhost
      register: result_shell
      failed_when: >
          ("No such file or directory" in result_shell.stdout) or
          (result_shell.stderr != '') or
          (result_shell.rc == 10)
      changed_when: false

    - name: debug result_shell.stdout
      debug:
        msg: "{{ result_shell.stdout | default('None', true) }}"
    - name: debug result_shell.stderr
      debug:
        msg: "{{ result_shell.stderr | default('None', true) }}"